name: PR validation on develop

on:
  pull_request:
    types: [opened, synchronize]
    branches: [develop]
    paths:
      - 'force-app/**'

jobs:
  validate-deployment-on-develop-org:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Install Salesforce CLI'
        run: |
          npm install @salesforce/cli --global

      - name: 'Installing java'
        run: |
          sudo apt-get update
          sudo apt install default-jdk

      - name: 'Installing SFDX scanner'
        run: sf plugins install @salesforce/sfdx-scanner

      - name: 'Populate auth file with SFDX_URL secret of integration org'
        shell: bash
        run: |
          echo ${{ secrets.SFDX_INTEGRATION_URL}} > ./SFDX_INTEGRATION_URL.txt

      - name: 'Authenticate to Integration Org'
        run: sfdx auth:sfdxurl:store -f ./SFDX_INTEGRATION_URL.txt -s -a integration

      - name: 'Run SFDX Scanner'
        run: |
          sfdx scanner:run --format sarif --target 'force-app/**/*.{cls,trigger}' --category "Design,Best Practices,Performance" --outfile 'apexScanResults.sarif'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: apexScanResults.sarif

      - name: 'Full Deploy to Integration Org'
        run: |
          sfdx force:source:deploy -p "force-app" --checkonly --testlevel RunLocalTests --json

      - name: 'Full Deploy Destructive Changes (if any)'
        run: |
          sfdx force:mdapi:deploy -d "force-app" --checkonly --ignorewarnings --json
